import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import SessionProvider from "../_components/SessionProvider";
import { getServerSession } from "next-auth";
import Navbar from "../_components/navigation/mainNav/Navbar";
import CategoryNav from "../_components/navigation/categoryNav/CategoryNav";
import MobileNavBar from "../_components/navigation/mobileNav/MobileNav";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider session={session}>
          <div className="hidden md:block">
            <Navbar />
          </div>
          <div className="block md:hidden">
            <MobileNavBar />
          </div>
          <CategoryNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
