import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Montserrat } from "next/font/google";
import SessionProvider from "../_components/SessionProvider";
import CategoryNav from "../_components/navigation/categoryNav/CategoryNav";
import Navbar from "../_components/navigation/mainNav/Navbar";
import MobileNavBar from "../_components/navigation/mobileNav/MobileNav";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";
import React from "react";
import { ReactQueryProvider } from "@/_components/ReactQueryProvider";
import { CartProvider } from "@/_providers/CartProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions as any);
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReactQueryProvider>
          <SessionProvider session={session as any}>
            <CartProvider>
              <div className="hidden md:block">
                <Navbar />
              </div>
              <div className="block md:hidden">
                <MobileNavBar />
              </div>
              <CategoryNav />
              {children}
            </CartProvider>
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
