import AccountSideBar from "@/_components/account/AccountSideBar";
import type { Metadata } from "next";
import "../globals.css";
import { getServerSession } from "next-auth";
import NotSignedIn from "@/_components/account/NotSignedIn";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AccountLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions as any);

  if (!session) {
    return <NotSignedIn />;
  }
  return (
    <section className="w-full">
      <AccountSideBar />
      {children}
    </section>
  );
}
